### ISSUE TITLE
[Dataset Label Mapping]

### ISSUE THREAD

**Issue by sara-02** [haroonshakeel/roman_urdu_hate_speech#1]
Hello guys, Thank you for sharing the annotated datasets for both tasks. It will be helpful if you could update the README.md with what those labels represent.
Eg: For task-1 what do labels 0/1 correspond to, which label is hate and which is non-hate. Also for task-2 what do the labels 0,1,2,3,4 represent (which one is abuse and which is sexism etc). 
While I can count each label and map it to the data overview provided In the table. For quick referencing and understanding it would be easier if those mappings were externally listed as well.

**Comment by haroonshakeel** [comment]
> Hello guys, Thank you for sharing the annotated datasets for both tasks. It will be helpful if you could update the README.md with what those labels represent.
> Eg: For task-1 what do labels 0/1 correspond to, which label is hate and which is non-hate. Also for task-2 what do the labels 0,1,2,3,4 represent (which one is abuse and which is sexism etc).
> While I can count each label and map it to the data overview provided In the table. For quick referencing and understanding it would be easier if those mappings were externally listed as well.

Hello Sara. Thank you for your comment. Kindly note that the labels mapping is already uploaded in "label_definitions.txt". Readme is updated to guide the readers.

**Comment by sara-02** [comment]
Thanks, I did not notice that file., my bad.
